project:
  type: website
website:
  title: "Kara Hoover"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Portfolio
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        href: https://github.com/kchoover14
format:
  html:
    theme: cerulean
    toc: false