project:
  type: website

website:
  title: "Kara Hoover"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Portfolio
      - icon: github
        href: https://github.com/kchoover14
        text: Github

format:
  html:
    theme: cerulean
    toc: false
